### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by xjx363631317** [falkowich/gvm-docker#1]
docker run it ：
Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o  -c config_file="/etc/postgresql/11/main/postgresql.conf"  exited with status 1: 
2019-12-03 08:30:59.220 UTC [25] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-12-03 08:30:59.220 UTC [25] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2019-12-03 08:30:59.220 UTC [25] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2019-12-03 08:30:59.238 UTC [25] FATAL:  could not open lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Permission denied
2019-12-03 08:30:59.238 UTC [25] LOG:  database system is shut down
pg_ctl: could not start server
Examine the log output.
   ...fail!
===> Checking if db is ready
psql: could not connect to server: Connection refused
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Creating database gvmd and settings
createuser: could not connect to database postgres: could not connect to server: Permission denied
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
createdb: could not connect to database template1: could not connect to server: Permission denied
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: Permission denied
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by falkowich** [comment]
This repo is still a big work in progress, perhaps things will start to look better soon..
Until then I close this issue, and if the problem persist after it goes "live" please reopen this issue

If you want to use a stable gvm10-docker you can look at https://github.com/falkowich/gvm10-docker until this gets more stable.
